# Generated by Django 5.0.1 on 2024-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarTrackingApp', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField()),
                ('ldrValue1', models.IntegerField()),
                ('ldrValue2', models.IntegerField()),
                ('servoAngle', models.FloatField()),
            ],
        ),
    ]
