# Generated by Django 5.0.1 on 2024-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarTrackingApp', '0003_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='username',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
